name: format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ocaml-tracing/ocaml-opentelemetry/ci-4.14:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - run: chown -R opam:opam .

      - run: su opam -c "opam exec -- make format-check"
